[workspace]
authors = ["Rohit Goswami <rgoswami[at]ieee.org>"]
channels = ["https://prefix.dev/rg-forge", "conda-forge", "https://conda.anaconda.org/metatensor"]
name = "rg-forge"
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64"]
version = "0.1.0"
description = "Forge for software distributed without official equivalents"

[tasks]
gen-gha = "nickel export --format yaml ci/gha/workflow.ncl -o .github/workflows/build.yml"

#  --experimental for nompi in context
[tasks.build-sccache]
# Cached build
# https://rattler.build/latest/tips_and_tricks/#using-sccache-or-ccache-with-rattler-build
args = ["pkg"]
cmd = "USE_SCCACHE=1 rattler-build build --experimental -m conda_build_config.yaml -m {{ pkg }}/variants.yaml --no-build-id --recipe {{ pkg }}"

[tasks.build-ci]
args = ["pkg", "target"]
cmd = "USE_SCCACHE=1 rattler-build build --experimental -m conda_build_config.yaml -m {{ pkg }}/variants.yaml --no-build-id --recipe {{ pkg }} --target-platform={{ target }} --skip-existing=all"

[tasks.build]
args = ["pkg"]
cmd = "rattler-build build --experimental -m conda_build_config.yaml -m {{ pkg }}/variants.yaml --no-build-id --recipe {{ pkg }}"

[dependencies]
rattler-build = ">=0.42.1,<0.43"
conda-index = ">=0.6.1,<0.7"
nickel = ">=9.9.9,<10"

[pypi-dependencies]
rgpycrumbs = { git = "https://github.com/HaoZeke/rgpycrumbs" }
