[workspace]
authors = ["Rohit Goswami <rgoswami[at]ieee.org>"]
channels = ["https://prefix.dev/rg-forge", "conda-forge", "https://conda.anaconda.org/metatensor"]
name = "rg-forge"
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64"]
version = "0.1.0"
description = "Forge for software distributed without official equivalents"

[tasks]
#  --experimental for nompi in context
build = "rattler-build build --experimental --recipe "
# Cached build
# https://rattler.build/latest/tips_and_tricks/#using-sccache-or-ccache-with-rattler-build
build-sccache = "USE_SCCACHE=1 rattler-build build --experimental --no-build-id --recipe "
build-all-sccache = "USE_SCCACHE=1 rattler-build build --experimental --no-build-id --skip-existing=all --recipe-dir ."
gen-gha = "nickel export --format yaml ci/gha/workflow.ncl -o .github/workflows/build.yml"

[dependencies]
rattler-build = ">=0.42.1,<0.43"
conda-index = ">=0.6.1,<0.7"
nickel = ">=9.9.9,<10"
